### ISSUE TITLE
Create script that checks for every RGB value

### ISSUE THREAD

**Issue by Zebiano** [zebscripts/AFK-Daily#11]
Since at least one RGB value is off after every new AFK Arena patch, I want to create a script to be run after every new patch that tells me which RGB values are wrong. This way, it'll be easier to fix those and update the main script.

**Comment by kevingrillet** [comment]
Maybe, adding a tolerance could be a good way to avoid this problem? [Example](https://stackoverflow.com/questions/9018016/how-to-compare-two-colors-for-similarity-difference/9085524#9085524) adapted in shell (hoping I didn't make any mistake)

```shell
#!/bin/bash

# pause
function pause {
  read -s -r -n 1 -p "Press any key to continue..."
  echo ""
}

# sqrt
# Params: color1 color2
# https://stackoverflow.com/a/59263103/7295428
function sqrt() {
	temp=$1
	if [ $temp -lt 0 ]; then temp="$(($temp * -1))"; fi
    divider=0
    while true; do
        divider="$(($divider + 1))"
        sqrt="$(($temp / $divider))"
        if [ $(($devider)) -eq $(($sqrt)) ]; then echo "OK"; break; fi
		if [ $(($devider)) -gt $(($sqrt)) ]; then echo "OK"; break; fi
		echo "$temp / $divider = $sqrt"
    done
    echo "$sqrt"
}

# colorDistance
# Params: color1 color2
function colorDistance() {
    color1=$1
    color2=$2
    # long rmean = ( (long)e1.r + (long)e2.r ) / 2;
    rmean="($((0x${color1:0:2})) + $((0x${color2:0:2}))) / 2"
    # long r = (long)e1.r - (long)e2.r;
    r="$((0x${color1:0:2})) - $((0x${color2:0:2}))"
    # long g = (long)e1.g - (long)e2.g;
    g="$((0x${color1:2:4})) - $((0x${color2:2:4}))"
    # long b = (long)e1.b - (long)e2.b;
    b="$((0x${color1:4:6})) - $((0x${color2:4:6}))"
    # return sqrt((((512+rmean)*r*r)>>8) + 4*g*g + (((767-rmean)*b*b)>>8));
    temp="$(((((512 + $rmean) * $r * $r) / 2) + 4 * $g * $g + (((767 - $rmean) * $b * $b) / 2)))"
	
	echo "sqrt $temp"
	sqrt "$temp"
}

colorDistance "aaf2bb" "aaf2bc"
```

It's as slow as it could be, but well, it's just an experiment...

**Comment by Zebiano** [comment]
Yeah, interesting Idea. I've thought about tolerances before as well, never tested them though. I do feel like that is a bit too complicated and unnecessary, as well as being slow as you mentioned. Maybe something like [this](https://stackoverflow.com/questions/22692134/detect-similar-colours-from-hex-values) would be more suited.

The alternative would be to write a "test" script that just checks for each RGB value, and warns whenever an RGB value is found that has changed. Not sure how feasible, time-consuming or practical this would be though.

**Also, just to make things clear:** I know the script has variables calling the values `RGB`, but in reality, they're Hex values... Though at this point I'm in too deep to change everything to the correct "name definition".

**Comment by kevingrillet** [comment]
It's fixed, and not as slow as I could imagine:

```sh
$ ./colorDiff.sh
input: 000000 000000
0

real    0m0.001s
user    0m0.000s
sys     0m0.000s
input: 000000 ffffff
6468

real    0m0.093s
user    0m0.093s
sys     0m0.000s
input: aaf2bb aaf2bc
17

real    0m0.000s
user    0m0.000s
sys     0m0.000s
Press any key to continue...

```

If it's only called when the specific color is not found, in my opinion being a little slow is not a problem...

HEX = RGB or something like RGB, just group characters 2 by 2, then convert into decimals and you get the colors.

**Comment by Zebiano** [comment]
Oh OK, that is indeed quicker than I also imagined. I guess it'll depend on the machine running the script anyways. I wonder how long it takes on an android phone.

Either way, that is a step in the right direction! I'll play a bit around with it too and see what I can find.

**Comment by kevingrillet** [comment]
```shell
#!/bin/bash

# pause
function pause {
  read -s -r -n 1 -p "Press any key to continue..."
  echo ""
}
# hexColorDelta
# Params: color1 color2
# https://stackoverflow.com/a/22692625/7295428
function hexColorDelta() {
    color1=$1
    color2=$2
    r=$((0x${color1:0:2} - 0x${color2:0:2}))
    g=$((0x${color1:2:2} - 0x${color2:2:2}))
    b=$((0x${color1:4:2} - 0x${color2:4:2}))
    d=$(((${r#-} + ${g#-} + ${b#-}) / 3))
    echo "$d"
}

# time hexColorDelta 000000 000000 # output: 0
# time hexColorDelta 000000 ffffff # output: 255
hexColorDelta aaf2bb aaf200

pause

```

**Comment by Zebiano** [comment]
Oh wow, thank you! After some testing, the [second method](https://github.com/zebscripts/AFK-Daily/issues/11#issuecomment-825666867) is way quicker! So that would be the one to use! My question now is, what does it actually do?

As far as I can tell, you're getting an `R`, `G` and `B` value by subtracting colour 2 from colour 1. Why are you adding `0x` to it though?

And what does this line do: `d=$(((${r#-} + ${g#-} + ${b#-}) / 3))`

**Comment by kevingrillet** [comment]
It's looking at the delta between R/G/B so some results are a bit "false" but it's easier than the first method.

I forgot to do some steps... and I needed to do some modifications... shell can't do float, so I need to do `* 100` in the last part and `(3 * 255)` to get a %.

```shell
#!/bin/bash
# https://www.shellcheck.net/

# colorDistance <COLOR1> <COLOR2>
# The result should be send to sqrt
# https://stackoverflow.com/a/9085524/7295428
function colorDistance() {
    color1=$1
    color2=$2
    rmean=$(((0x${color1:0:2} + 0x${color2:0:2}) / 2))
    r=$((0x${color1:0:2} - 0x${color2:0:2}))
    g=$((0x${color1:2:2} - 0x${color2:2:2}))
    b=$((0x${color1:4:2} - 0x${color2:4:2}))
    d=$(((((512 + rmean) * r * r) / 2) + 4 * g * g + (((767 - rmean) * b * b) / 2)))
    echo $d
}
# time colorDistance 000000 000000 # output: 0
# time colorDistance 000000 ffffff # output: 41843587 (sqrt > 6468)

# hexColorDelta <COLOR1> <COLOR2>
# https://stackoverflow.com/a/22692625/7295428
function hexColorDelta() {
    color1=$1
    color2=$2
    r=$((0x${color1:0:2} - 0x${color2:0:2}))
    r=$((255-${r#-}))
    g=$((0x${color1:2:2} - 0x${color2:2:2}))
    g=$((255-${g#-}))
    b=$((0x${color1:4:2} - 0x${color2:4:2}))
    b=$((255-${b#-}))
    d=$((((r + g + b ) * 100) / (3 * 255)))
    echo $d
}
# time hexColorDelta 000000 000000 # output: 100    => same color = 100%
# time hexColorDelta ff0000 0000ff # output: 33     => G = 0 in both so 33%
# time hexColorDelta ffff00 0000ff # output: 0      => opposite = 0%
# time hexColorDelta 000000 ffffff # output: 0      => opposite = 0%

```

`0x` is to convert Hex into Dec ([source](https://stackoverflow.com/a/22863296/7295428))
`${r#-}` is to get the absolute value ([source](https://stackoverflow.com/a/47240327/7295428))

**Comment by Zebiano** [comment]
Damn, that is perfect! I was trying to code something like that but was struggling a bit. And I love that it is really quick to calculate as well! I feel like this could be the way to go. Maybe implement like a 90% chance. If less than 90 then it's considered wrong, else keep going.

**Comment by kevingrillet** [comment]
If you want to cry (or try to see which one is the best, but most of them play with `sqrt`, so they will be slower), I did some experiments with colors XD

https://github.com/kevingrillet/ShellUtils/blob/main/utils_colors.sh

**Comment by kevingrillet** [comment]
A bit more compact version:
```shell
# sRGBColorDelta <COLOR1> <COLOR2>
# https://stackoverflow.com/a/22692625/7295428
# 0 means opposit colors, 100 means same colors
sRGBColorDelta() {
    r=$((0x${1:0:2} - 0x${2:0:2}))
    g=$((0x${1:2:2} - 0x${2:2:2}))
    b=$((0x${1:4:2} - 0x${2:4:2}))
    d=$((((765 - (${r#-} + ${g#-} + ${b#-})) * 100) / 765))                     # 765 = 3 * 255
    echo $d
}
```

**Comment by Zebiano** [comment]
I will also start implementing this after most of the major updates and PRs for the script are done now. Thank you!

**Comment by kevingrillet** [comment]
I did implement it for testing purposes during the refacto, it's just showing the delta, not actually testing it, but I think it will be possible
