### ISSUE TITLE
Arena attack don't work

### ISSUE THREAD

**Issue by korigard** [zebscripts/AFK-Daily#112]
[TASK]  Checking folders... Done!
[TASK]  Checking for adb... Found locally!
[TASK]  Checking for updates... Checked/Updated!
[TASK]  Checking for setup updates...
[INFO]  ./config/config-arena.ini updated
        Checked/Updated!
[TASK]  Searching for config/config-arena.ini... Found!
[TASK]  Validating config/config-arena.ini... Passed!
[TASK]  Checking Line endings of file account-info/acc.ini... Passed!
[TASK]  Checking Line endings of file config/config-arena.ini... Passed!
[TASK]  Checking Line endings of file afk-daily.sh... Passed!
[TASK]  Checking last time script was run... Done!
[TASK]  Restarting ADB... Restarted!
[TASK]  Searching for device through ADB... Found Bluestacks!

[INFO]  Platform: Bluestacks
[INFO]  Script Directory: storage/emulated/0/scripts/afk-arena
[INFO]  Latest tested patch: 1.71.04

[INFO]  Starting script... (Tue Sep 21 08:30:30 CEST 2021)
[INFO]  Fight Campaign: OFF
[INFO]  Weekly: OFF

[DONE]  Switched to the Campaign Tab.
[DONE]  Switched to the Dark Forest Tab.
[DONE]  Switched to the Campaign Tab.
[DONE]  Switched to the Dark Forest Tab.
[INFO]  Fighting in the Arena Of Heroes 50 time(s).
[DONE]  Checked the Arena of Heroes out. [0 W / 0 L]

[INFO]  End of script! (Tue Sep 21 08:33:32 CEST 2021)

------------------------------------------------------------------------------------- 
```
config-arena.ini

# --- CONFIG: Modify accordingly to your game! --- #
# --- Use this link for help: https://github.com/zebscripts/AFK-Daily/wiki/Config --- #
# Player
canOpenSoren=false
arenaHeroesOpponent=5

# General
waitForUpdate=true
endAt=campaign
guildBattleType=quick
allowCrystalLevelUp=false

# Repetitions
maxCampaignFights=0
maxKingsTowerFights=0
totalAmountArenaTries=50
totalAmountTournamentTries=0
totalAmountGuildBossTries=0
totalAmountTwistedRealmBossTries=0

# Store
buyStoreDust=false
buyStorePoeCoins=false
buyStorePrimordialEmblem=false
buyStoreAmplifyingEmblem=false
buyStoreSoulstone=false
buyStoreLimitedGoldOffer=false
buyStoreLimitedDiamOffer=false
buyWeeklyGuild=false
buyWeeklyLabyrinth=false

# Towers
doMainTower=true
doTowerOfLight=true
doTheBrutalCitadel=true
doTheWorldTree=true
doCelestialSanctum=true
doTheForsakenNecropolis=true
doInfernalFortress=true

# --- Actions --- #
# Campaign
doLootAfkChest=false
doChallengeBoss=false
doFastRewards=false
doCollectFriendsAndMercenaries=false

# Dark Forest
doSoloBounties=false
doTeamBounties=false
doArenaOfHeroes=true
doLegendsTournament=false
doKingsTower=false

# Ranhorn
doGuildHunts=false
doTwistedRealmBoss=false
doBuyFromStore=false
doStrengthenCrystal=false
doTempleOfAscension=false
doCompanionPointsSummon=false
doCollectOakPresents=false

# End
doCollectQuestChests=false
doCollectMail=false
doCollectMerchantFreebies=false
```

**Comment by Zebiano** [comment]
What does the script do? Does it enter the arena? And if it does, what does it do next?

**Comment by korigard** [comment]
it only enter end exit... doesn't attack.

**Comment by korigard** [comment]
[log.txt](https://github.com/zebscripts/AFK-Daily/files/7207978/log.txt)
here log

**Comment by Zebiano** [comment]
Thank you for attaching a log! After taking a look at it, it looks like we need to update some RGB values. Though I do want to try this out and check if I have the same problem or not. Will get back to you hopefully this week.

**Comment by Zebiano** [comment]
Well, unfortunately I am being able to fight in the Arena of Heroes. I'll get in contact with you on Discord to try and solve this and will later post the solution here.

**Comment by korigard** [comment]
i change my language to english and all work fine... i don't know why...

**Comment by kevingrillet** [comment]
Since we are based on color of specific pixels I think it's only working for the game in English :/

**Comment by Zebiano** [comment]
That is really interesting... Maybe some fonts are longer and overlap specific HEX checks we do...? Nice find @korigard! Will update the requirements page.
