### ISSUE TITLE
Crashing cause of update

### ISSUE THREAD

**Issue by pikachukaki** [zebscripts/AFK-Daily#128]
Im having this issue today cause the script needs update it says something about git not installed and crashes.
![Untitled](https://user-images.githubusercontent.com/3009586/137464848-d6deea1e-0a8a-44df-b9b7-4b631ee0f3a0.png)

**Comment by pikachukaki** [comment]
> Hey there! What do you mean with "crashes"? From the screenshot you sent, everything should be working fine. Just wait until the update is done. The warning is OK.

Yeah if I keep pressing the cursor on the window it stays like this so I manage to take a screenshot if I didn't do anything it show this and then the window close.

**Comment by Zebiano** [comment]
Closing issue for now. Feel free to reopen when necessary.
