### ISSUE TITLE
Implement flag to run hexdump with su

### ISSUE THREAD

**Issue by Zebiano** [zebscripts/AFK-Daily#146]
This issue originated from #144.

We need to implement a new flag `-g` for `deploy.sh` and `afk-daily.sh` that will, when used, change the `afk-daily.sh` file to run `hexdump` with `su -c`. I imagine `sed` will be handy for this.

**Comment by kevingrillet** [comment]
Mmh, why not just add a variable and a condition?
```sh
readHEX() {
    offset=$((DEVICEWIDTH * $2 + $1 + 3))
    if [ "$suhexdump" = true ]; then
        HEX=$(dd if="$SCREENSHOTLOCATION" bs=4 skip="$offset" count=1 2>/dev/null | su hexdump -C)
    else
        HEX=$(dd if="$SCREENSHOTLOCATION" bs=4 skip="$offset" count=1 2>/dev/null | hexdump -C)
    fi
    HEX=${HEX:9:9}
    HEX="${HEX// /}"
}
```

**Comment by Zebiano** [comment]
True, `sed` is definitely overkill here.

**Comment by GaryStar** [comment]
Don't expose the option as a flag for the user.
Just run at start of the script ```adb shell hexdump --help``` and check the resulting text for ```permisison denied```. if it's found. just set that variable to ```true```

**Comment by Zebiano** [comment]
I usually don't fancy changing code that may affect others, especially since I cannot validate it myself as I don't have the `Permission denied` error. So I prefer to add a flag, this way I'm sure existing users will continue having the same experience as before, and those who want to make use of the feature simply run it with the desired flag. The risk is in my opinion usually not high enough for me to not implement new features like these with a flag.

Even though after having said all that, I've decided to give it a try this time and hopefully it all goes well for existing users, as well for those who need to run `hexump` with `su`.
