### ISSUE TITLE
make update to work automatically and auto-restart script after

### ISSUE THREAD

**Issue by GaryStar** [zebscripts/AFK-Daily#149]
To allow the script to work in an automated environment (via a cronjob for ex) can you please add an argument to instruct the script to auto-update if needed (don't wait for user input) and at the end just restart itself (you can use ```exec "$0" "$@"``` for this)

**Comment by kevingrillet** [comment]
I wanted to do that, but I didn't know how to restart the script XD

**Comment by GaryStar** [comment]
the script still stops and wait for user input if an update is found.
please add a script argument to allow automatically updates and not wait for user input.

**Comment by Zebiano** [comment]
The script only asks for user input if something doesn't go as planned @GaryStar:
- In case you have local changes
- In case it did not manage to update the script

I do not plan on changing these by the way. I could add a flag to `force` an update if found, but I'm not sure if that's worth it for what it is. I'd rather have you check what the script is asking you to do, as it's probably one of the above.

**Comment by GaryStar** [comment]
Thank you for your response.
This makes sense then. I'm running the script using a simple wrapper that will first replace some things in the main script. For example I replace all tower battles logs from ```INFO``` to ```DONE``` so ```git status``` will always return something hence the prompt on update. 
No matter, I will also replace ```read -r answer``` with ```answer="y"``` :)
