### ISSUE TITLE
click twice on changing tabs

### ISSUE THREAD

**Issue by GaryStar** [zebscripts/AFK-Daily#151]
When clicking on tabs (Campaign, Dark Forest or Ranhorn) click twice with a small delay to close any offer popup than can appear.

**Comment by Zebiano** [comment]
I'm guessing the current behaviour would restart the whole app?

**Comment by GaryStar** [comment]
yes.. it restarts the game but then after restart when tries again to click on tabs the popup appears again because was not closed last time (app was just closed and restarted). this will result again in error processing pixels and app will be restarted.. this will continue in loop until you stop the script and manually click to close the popup..  
but clicking twice on the bottom part of the screen (on tabs) will first close the popup and then actually click on tab. if the popup is not there, no harm done, it will click twice on the tab.
