### ISSUE TITLE
check if "arena of heroes" is first or second tab

### ISSUE THREAD

**Issue by GaryStar** [zebscripts/AFK-Daily#153]
If an event is happening in "Arena of Heroes" (for ex. Heroes of Esperia"), the tab to enter Arena of Heroes is second, after the one for the event.
Based on pixel colors, check the location of "Arena of Heroes" tab.
Also this computation is needed to correctly locate "Legends' Challenger Tournament" tab

![Screenshot_2022 01 30_09 43 48 652](https://user-images.githubusercontent.com/7147048/151691216-ab244188-04e2-44aa-94e7-5454bba501de.png)

**Comment by Zebiano** [comment]
This is already implemented. Run the script with the `-e hoe` flag and it should fix the problem. I will also push an update where by default it knows that the event is active, meaning you won't have to run it with this flag.
