### ISSUE TITLE
results for tower fights displayed as INFO

### ISSUE THREAD

**Issue by GaryStar** [zebscripts/AFK-Daily#154]
Why the results for tower fights are displayed in log as [INFO] and not as [DONE] as for the other fights?
One would expected an [INFO] message when an action is started and a [DONE] one when is finished, right?

![Screenshot 2022-01-31 134028](https://user-images.githubusercontent.com/7147048/151788206-4e8f50fd-d819-4ebc-a261-39cb430ef19f.png)

**Comment by Zebiano** [comment]
Yes, you are correct. Let's change it for consistency reasons.

**Comment by GaryStar** [comment]
fights in Main Tower are still displayed as [INFO]

![Screenshot 2022-01-31 214701](https://user-images.githubusercontent.com/7147048/151862102-79302964-e23f-4009-999a-4c15e7c40b3a.png)

**Comment by Zebiano** [comment]
Lol sorry, my bad. Completely missed the main tower. Should be fixed by now.
