### ISSUE TITLE
[BUG] Stuck at Twisted realms

### ISSUE THREAD

**Issue by kevingrillet** [zebscripts/AFK-Daily#161]
[Original message](https://discord.com/channels/859136061049143307/859139263958614047/956230746564087808)

**Describe the bug**

Since the last patch with auto battle, the script is stuck here.

**Expected behavior**

Should work the same way as before ;)

**Additional information**

I think it's the X value right here that require an update:
https://github.com/zebscripts/AFK-Daily/blob/4fb6a676d4702f714190df2d9dd07322bd31f1a7/afk-daily.sh#L1576

Btw, tower seems to have similar update, but it's working here 😮 
https://github.com/zebscripts/AFK-Daily/blob/4fb6a676d4702f714190df2d9dd07322bd31f1a7/afk-daily.sh#L1054

**Comment by Zebiano** [comment]
Thanks for the issue. It's actually simply [this HEX check](https://github.com/zebscripts/AFK-Daily/blob/master/afk-daily.sh#L1570) that is messing it up. Will be fixed in the next commit!
