### ISSUE TITLE
The bot stops as soon as the user receives LvL.

### ISSUE THREAD

**Issue by 53jk1** [zebscripts/AFK-Daily#20]
The bot stops as soon as the user receives LvL.

**Comment by Zebiano** [comment]
Sorry for the late response. I somehow did not get any type of notification from this issue.

Either way, you're absolutely right! I need to fix this is the future. You can bypass this issue by loading up the game before running the script, just to check if there are any pop-ups (maybe a new hero came out and Lilith really wants you to buy them), as well as collecting the AFK rewards once. This way you can check if a level-up actually happens or not, and take care of it yourself. Most likely running the script after collecting the rewards won't make you level-up.
