### ISSUE TITLE
Collect Merchants not properly working

### ISSUE THREAD

**Issue by kevingrillet** [zebscripts/AFK-Daily#39]
I don't know if I'm the only one, but the Free bundle is much lower than your tap: `input tap 200 750 # Free bundle`

![Bluestacks_2021-04-21_10-05_3Y0HU](https://user-images.githubusercontent.com/7203617/115519051-22067580-a289-11eb-8380-5eeda5037d44.png)

**Comment by Zebiano** [comment]
Oh, interesting. Yes, for me that is not the case at all. That makes things difficult because everyone might have the free bundles in different locations. Why is it like that though? What are those special daily Bundles? Have you spent money on the game at least once yet? I'm guessing the game gives you special bundles to try and convince you to spend again?

**Comment by Zebiano** [comment]
I'll make a quick commit throughout the day that adds "collecting free rewards" as a variable inside `config.sh`. This way users can decide if they want to/can collect the rewards, while also potentially saving users from spending money without their consent.

**Comment by kevingrillet** [comment]
Yep, I did spend few € long time ago in the game, so maybe it comes from that :/

**Comment by Zebiano** [comment]
For now, I'll work around this issue by defaulting the collection of merchants to `false` and letting users know it only works when the merchants page looks like this:

![Screenshot_2021 04 21_12 47 00 977](https://user-images.githubusercontent.com/9255144/115548762-c0053a80-a29f-11eb-81bf-799599b53126.png)

If most users have their merchant page looking like [this one](https://github.com/zebscripts/AFK-Daily/issues/39#issue-863636316), I could think about adding it to the script.

**Comment by kevingrillet** [comment]
I will try tomorrow by using `input tap 200 1100 # Free bundle`

![Bluestacks_2021-04-21_14-27_JRlfE](https://user-images.githubusercontent.com/7203617/115553526-cac6cc00-a2ad-11eb-889a-868f6f2315a5.png)

**Comment by delgatojr** [comment]
HI. I fixed this issue in my fork. I made a check for the RGB on the special bundle.

**Comment by Zebiano** [comment]
Oh, thanks @delgatojr! Do you mind making a pull request with the changes then?

**Comment by Zebiano** [comment]
@kevingrillet The above PR fixes this issue. It's been merged to main by now. I'd appreciate it if you could test it on your account and let us know if it worked!

**Comment by kevingrillet** [comment]
Ok, I will test it tomorrow 👍

**Comment by kevingrillet** [comment]
It's working \o/

```text
Task: Checking for adb...
Success: Found locally!
Task: Checking for updates...
Success: Checked/Updated!
Task: Searching for config.sh file...
Success: Found!
Task: Validating config.sh...
Success: Passed!
Task: Checking Line endings of file config.sh...
Success: Passed!
Task: Checking Line endings of file afk-daily.sh...
Success: Passed!
Task: Restarting ADB...
Success: Restarted!
Task: Searching for device through ADB...
Success: Found Bluestacks!

Info: Platform: Bluestacks
Info: Script Directory: storage/emulated/0/scripts/afk-arena

[INFO] Starting script... (Thu Apr 22 09:13:22 CEST 2021)

[OK] Switched to the Campaign Tab.
[OK] Switched to the Dark Forest Tab.
[OK] Switched to the Ranhorn Tab.
[OK] Switched to the Campaign Tab.
[OK] Switched to the Ranhorn Tab.
[OK] Collected daily/weekly/monthly offer.
[OK] Switched to the Dark Forest Tab.

[INFO] End of script! (Thu Apr 22 09:14:15 CEST 2021)
```
