### ISSUE TITLE
The Oak Inn optimisation

### ISSUE THREAD

**Issue by kevingrillet** [zebscripts/AFK-Daily#40]
Since few patches, the best reward awaits you in your Inn reception, so you could just detect the red pixel and collect?

**Comment by Zebiano** [comment]
Yes, I've realised those are there now. But the script still won't be able to use that, as the heroes carrying the presents move around. I can't test for a certain pixel colour, as it will change. I could make the script tap randomly across the X-axis, but I'd rather have it traverse friends and make sure to collect daily presents, instead of trying to blindly collect presents without really knowing if it managed to do so or not. And since this would only change the amount of time the script runs, I've decided to ignore that new feature and rely on the old method.

**Comment by kevingrillet** [comment]
Can the pixel detect be used in the opposite way? As it's done in [autoit](https://www.autoitscript.com/autoit3/docs/functions/PixelSearch.htm). For example [finding color in image](https://askubuntu.com/questions/1136514/is-it-possible-to-get-the-location-of-a-specific-color-in-an-image-using-bash).

**Comment by Zebiano** [comment]
The first method you propose is not ideal, as the script would have to check every pixel from the rectangle manually, which takes way too much time. It might take less time to check those pixels than to go through every friend though. Not sure about that.

The second method is not applicable to this script, as it has to run on an emulator. And I doubt Android has `ImageMagick` natively, nor that it's possible to install it.

I'm working on a separate project, a sort of AFK-Daily 2 that doesn't rely on Android's shell system, but instead on NodeJS Packages and runs off the computer. But it's still in very early development, and I doubt I'll be able to release it any time soon. But whenever I do release it, it should be possible to make use of the rewards waiting at the Oak Inn reception.

**Comment by kevingrillet** [comment]
Did try but still not working for me :/

```text
Task: Checking for adb...
Success: Found locally!
Task: Checking for updates...
Success: Checked/Updated!
Task: Searching for config.sh file...
Success: Found!
Task: Validating config.sh...
Success: Passed!
Task: Checking Line endings of file config.sh...
Success: Passed!
Task: Checking Line endings of file afk-daily.sh...
Success: Passed!
Task: Restarting ADB...
Success: Restarted!
Task: Searching for device through ADB...
Success: Found Bluestacks!

Info: Platform: Bluestacks
Info: Script Directory: storage/emulated/0/scripts/afk-arena

[INFO] Starting script... (Thu Apr 22 09:08:45 CEST 2021)

[OK] Switched to the Campaign Tab.
[OK] Switched to the Dark Forest Tab.
[OK] Switched to the Ranhorn Tab.
[OK] Switched to the Campaign Tab.
[OK] Switched to the Campaign Tab.
[OK] Switched to the Dark Forest Tab.
[OK] Switched to the Ranhorn Tab.
[WARN] Couldn't collect Oak Inn presents, sowy.
[OK] Attempted to collect Oak Inn presents.
[OK] Switched to the Dark Forest Tab.

[INFO] End of script! (Thu Apr 22 09:10:11 CEST 2021)
```
