### ISSUE TITLE
Check if x2 or x4 enabled + battle skip

### ISSUE THREAD

**Issue by kevingrillet** [zebscripts/AFK-Daily#46]
It could be useful to always be in x4 (or x2 for lower levels) for battles (Campaign, Guild boss, Twisted Realm Boss), and skip every battle possible (Arena Of Heroes, ~~Legends Tournament [already done]~~)

![Bluestacks_2021-04-23_08-51_Bl4Ol](https://user-images.githubusercontent.com/7203617/115831154-7f2d3300-a411-11eb-84dc-3308ea947d5b.png)

**Comment by Zebiano** [comment]
Agreed!

**Comment by kevingrillet** [comment]
Still missing the Auto... rahhhhhh totally forgot about it :D

![Bluestacks_2021-04-25_14-15_Bg0oI](https://user-images.githubusercontent.com/7203617/115992976-b433b400-a5d0-11eb-9007-d3fed6014f74.png)
