### ISSUE TITLE
2 settings for Arena and Legends tries

### ISSUE THREAD

**Issue by kevingrillet** [zebscripts/AFK-Daily#47]
Today, it's set by `totalAmountArenaTries=2+0`.

For Arena Of Heroes i can do up to 900 fights with my tickets.

![Bluestacks_2021-04-23_11-28_5pogQ](https://user-images.githubusercontent.com/7203617/115851286-0f29a780-a427-11eb-8068-58462b1c6187.png)

But for Legends Tournament we don't have any type of ticket, so we will always be stuck by the diamonds, which I don't want to use here 👎 

```shell
# Does the daily Legends tournament battles. Params: startFromTab
function legendsTournament() {

    ...

    # Repeat a battle for as long as totalAmountArenaTries
    local COUNT=0
    until [ "$COUNT" -ge "$totalAmountArenaTries-2" ]; do
```

**Comment by Zebiano** [comment]
Oh, so you want to have two separate settings for fighting in the Arena and the tournament. That also makes sense and should be easily done. I can try and tackle this whenever the latest PRs get merged!
