### ISSUE TITLE
Strenghen Crystal break on level up 👎 

### ISSUE THREAD

**Issue by kevingrillet** [zebscripts/AFK-Daily#50]
I did miss the confirm window when you level up...

**Comment by Zebiano** [comment]
In my eyes it was kind of an intended feature, as the player would not level up the crystal, but instead just strengthen it. If we add this feature of also leveling up, I'll want to add a variable to let players choose if they want to level it up or not inside the `config.sh`. Maybe something like `allowCrystalLevelUp`.

**Comment by delgatojr** [comment]
I would really like this feature. Great idea!
