### ISSUE TITLE
Stuck in Legends Tournament

### ISSUE THREAD

**Issue by kevingrillet** [zebscripts/AFK-Daily#67]
When you don't have any try remaining you end stuck after the click that is supposed to start the fight:

<details>
<summary>config.sh</summary>

```shell
# --- CONFIG: Modify accordingly to your game! Use this link for help: https://github.com/zebscripts/AFK-Daily#configvariables --- #
# Player
canOpenSoren=false
arenaHeroesOpponent=5

# General
waitForUpdate=true
endAt="championship"

# Repetitions
maxCampaignFights=0
maxKingsTowerFights=0
totalAmountArenaTries=2+1
totalAmountGuildBossTries=0

# Store
buyStoreDust=false
buyStorePoeCoins=false
buyStoreEmblems=false

# --- Actions --- #
# Campaign
doLootAfkChest=false
doChallengeBoss=false
doFastRewards=false
doCollectFriendsAndMercenaries=false

# Dark Forest
doSoloBounties=false
doTeamBounties=false
doArenaOfHeroes=false
doLegendsTournament=true
doKingsTower=false

# Ranhorn
doGuildHunts=false
doTwistedRealmBoss=false
doBuyFromStore=false
doStrengthenCrystal=false
doCompanionPointsSummon=false
doCollectOakPresents=false # Only works if "Hide Inn Heroes" is enabled under "Settings -> Memory"

# End
doCollectQuestChests=false
doCollectMail=false
doCollectMerchantFreebies=false
```

</details>

![mintty_2021-05-03_17-02_iAvwE](https://user-images.githubusercontent.com/7203617/116893568-67d02000-ac31-11eb-81ac-c14262aef607.png)

**Comment by Zebiano** [comment]
Thanks for this issue, that would make sense. I think we can make use of the newly added `waitForBattle()` function and add a max amount of tries. Or make a check for the blue button on the bottom that is see able on your screenshot. 

Also, how did this end up happening? Did you put the wrong amount in `totalAmountArenaTries`?

**Comment by kevingrillet** [comment]
I was trying to do `totalAmountArenaTries = 2 (default)+7 (VIP)+2 (free tickets / day)`
But it's not working, I don't remember the number of tournament free entries.

**Comment by Zebiano** [comment]
Interesting. OK, will try to fix this eventually!
