### ISSUE TITLE
Create flags for running the script

### ISSUE THREAD

**Issue by Zebiano** [zebscripts/AFK-Daily#7]
Use getopts for this.

**Comment by Zebiano** [comment]
I don't really remember what kind of flags I wanted to use, so closing this for now.

**Comment by Zebiano** [comment]
Actually, I remember again: Flags could be useful to start script from a certain part, or run script for certain parts only. For example `afk-daily.sh --startFrom arena` or `afk-daily.sh --arena --bounties --guildHunts`.

**Comment by kevingrillet** [comment]
Done with the new `config.sh`?
