### ISSUE TITLE
permission git

### ISSUE THREAD

**Issue by rafalohaki** [zebscripts/AFK-Daily#70]
Task: Checking Line endings of file config.sh...
head: cannot open 'config.sh' for reading: Permission denied
Success: Passed!
Task: Checking Line endings of file afk-daily.sh...
head: cannot open 'afk-daily.sh' for reading: Permission denied
using git bash

**Comment by Zebiano** [comment]
Hm, weird. Try running Git Bash with administrator rights, please.

**Comment by rafalohaki** [comment]
i have no permission to config.sh
I created config.sh again and tried but denied access

**Comment by rafalohaki** [comment]
-rw-r--r-- 1 rafal 197609  1095 May 10 10:24 LICENSE
-rw-r--r-- 1 rafal 197609 25098 May 10 10:24 README.md
drwxr-xr-x 1 rafal 197609     0 May 10 11:42 adb/
-rwxr-xr-x 1 rafal 197609 46124 May 10 10:24 afk-daily.sh*
-rw-r--r-- 1 rafal 197609  1022 May 10 12:41 config.sh
-rwxr-xr-x 1 rafal 197609 11878 May 10 10:24 deploy.sh*
drwxr-xr-x 1 rafal 197609     0 May 10 10:24 lib/

**Comment by kevingrillet** [comment]
Could you please send the result of the following commands [`whoami`](https://explainshell.com/explain?cmd=whoami) and [`ls -l`](https://explainshell.com/explain?cmd=ls+-l)?
It should resemble something like that:
```text
$ whoami
kevin

$ ls -l
total 92
-rw-r--r-- 1 kevin 197609  1095 Apr 22 19:17 LICENSE
-rw-r--r-- 1 kevin 197609 25098 Apr 30 09:31 README.md
drwxr-xr-x 1 kevin 197609     0 Apr 22 19:17 adb/
-rwxr-xr-x 1 kevin 197609 44514 May  3 16:32 afk-daily.sh*
-rw-r--r-- 1 kevin 197609   990 May  4 13:26 config.sh
-rwxr-xr-x 1 kevin 197609 11878 May  2 20:33 deploy.sh*
drwxr-xr-x 1 kevin 197609     0 Apr 22 19:17 lib/

```

**Comment by rafalohaki** [comment]
> 
> 
> Could you please send the result of the following commands [`whoami`](https://explainshell.com/explain?cmd=whoami) and [`ls -l`](https://explainshell.com/explain?cmd=ls+-l)?
> It should resemble something like that:
> 
> ```
> $ whoami
> kevin
> 
> $ ls -l
> total 92
> -rw-r--r-- 1 kevin 197609  1095 Apr 22 19:17 LICENSE
> -rw-r--r-- 1 kevin 197609 25098 Apr 30 09:31 README.md
> drwxr-xr-x 1 kevin 197609     0 Apr 22 19:17 adb/
> -rwxr-xr-x 1 kevin 197609 44514 May  3 16:32 afk-daily.sh*
> -rw-r--r-- 1 kevin 197609   990 May  4 13:26 config.sh
> -rwxr-xr-x 1 kevin 197609 11878 May  2 20:33 deploy.sh*
> drwxr-xr-x 1 kevin 197609     0 Apr 22 19:17 lib/
> ```

tried to chmod -x config.sh but nothing change

**Comment by kevingrillet** [comment]
Maybe a folder right? `ls -al`
```text
$ ls -al
total 898
drwxr-xr-x 1 kevin 197609     0 May 10 12:40 ./
drwxr-xr-x 1 kevin 197609     0 May  5 09:36 ../
-rw-r--r-- 1 kevin 197609    11 May  2 15:27 .afkscript.tmp
drwxr-xr-x 1 kevin 197609     0 May 10 10:07 .git/
-rw-r--r-- 1 kevin 197609    72 Apr 29 08:57 .gitignore
-rw-r--r-- 1 kevin 197609  1095 Apr 22 19:17 LICENSE
-rw-r--r-- 1 kevin 197609 25098 Apr 30 09:31 README.md
drwxr-xr-x 1 kevin 197609     0 Apr 22 19:17 adb/
-rwxr-xr-x 1 kevin 197609 44514 May  3 16:32 afk-daily.sh*
-rw-r--r-- 1 kevin 197609   990 May  4 13:26 config.sh
-rwxr-xr-x 1 kevin 197609 11878 May  2 20:33 deploy.sh*
drwxr-xr-x 1 kevin 197609     0 Apr 22 19:17 lib/

```

**Comment by rafalohaki** [comment]
seems config.sh isnt visible from command git ls-files --stage
$ git ls-files --stage
100644 79a095ea369e42bc2fc5c07014f139e058b1dedf 0       .gitignore
100644 e8524e83dfe79f5c1bc8dfbded487dac75796637 0       LICENSE
100644 d4e504d058350b7c33a9261b1e74f39a6931ec4d 0       README.md
100644 8f1ec69ecf38616310126bed3fbb0978e74a75ac 0       afk-daily.sh
100644 2288c5fc442ea3a87b2a72a37d8f1897608b80e7 0       deploy.sh
100644 9d3ecaf4821b1a7dca4e52389e2716430c4b9c59 0       lib/print.sh

rafal@Autarch-HP MINGW64 ~/Downloads/AFK-Daily (master)
$ ls -al
total 149
drwxr-xr-x 1 rafal 197609     0 May 10 12:41 ./
drwxr-xr-x 1 rafal 197609     0 May 10 12:23 ../
drwxr-xr-x 1 rafal 197609     0 May 10 12:39 .git/
-rw-r--r-- 1 rafal 197609    72 May 10 10:24 .gitignore
-rw-r--r-- 1 rafal 197609  1095 May 10 10:24 LICENSE
-rw-r--r-- 1 rafal 197609 25098 May 10 10:24 README.md
drwxr-xr-x 1 rafal 197609     0 May 10 11:42 adb/
-rwxr-xr-x 1 rafal 197609 46124 May 10 10:24 afk-daily.sh*
-r--r--r-- 1 rafal 197609  1022 May 10 12:41 config.sh
-rwxr-xr-x 1 rafal 197609 11878 May 10 10:24 deploy.sh*
drwxr-xr-x 1 rafal 197609     0 May 10 10:24 lib/

**Comment by rafalohaki** [comment]
my full outup after ./deploy in git bash
Task: Checking for adb...
Success: Found locally!
Task: Searching for config.sh file...
Success: Found!
Task: Validating config.sh...
Success: Passed!
Task: Checking Line endings of file config.sh...
head: cannot open 'config.sh' for reading: Permission denied
Success: Passed!
Task: Checking Line endings of file afk-daily.sh...
head: cannot open 'afk-daily.sh' for reading: Permission denied
Success: Passed!
Task: Checking last time script was run...
Task: Restarting ADB...
Success: Restarted!
Task: Searching for device through ADB...
Success: Found Bluestacks!

Info: Platform: Bluestacks
Info: Script Directory: storage/emulated/0/scripts/afk-arena

sh: storage/emulated/0/scripts/afk-arena/afk-daily.sh: No such file or directory

**Comment by rafalohaki** [comment]
uninstalled git, downloaded portable git, opened git bash as admin and now its working

**Comment by Zebiano** [comment]
I'm happy to hear you managed to solve it! Any idea/hint as to why this wasn't working before @rafalohaki?
