### ISSUE TITLE
Stuck at popups

### ISSUE THREAD

**Issue by fandy** [zebscripts/AFK-Daily#74]
Script stops at the start of the game event popups:

![image](https://user-images.githubusercontent.com/19108762/121981862-75161980-cd5c-11eb-8fde-3324ae0a3343.png)

**Comment by Zebiano** [comment]
Hey there Fandy! Thank you for this issue.

When did it pop up? Right at the beginning when you launch the game, or did it pop up during script execution?

**Comment by fandy** [comment]
> Hey there Fandy! Thank you for this issue.
> 
> When did it pop up? Right at the beginning when you launch the game, or did it pop up during script execution?

Right when I launched the game.

**Comment by Zebiano** [comment]
I see. It's always a bit difficult to take care of things like these, as they are very hit and miss. I do have an idea how to fix it, I'll just have to test it out. For now I ask you to open the game before running the script and simply making sure to close any open pop ups. This should prevent them from appearing when running the script afterwards.

**Comment by kevingrillet** [comment]
With the error handling it's working a bit better :p

But the clean way should be looking for the color in the blurry button at the bottom & tap while it's this color

**Comment by Zebiano** [comment]
A dirty way could be to simply tap on the campaign button three times to close anything that pops up. Lately, it's been quite annoying actually, too many pop-ups...
