### ISSUE TITLE
Use 4x speed during battles

### ISSUE THREAD

**Issue by fandy** [zebscripts/AFK-Daily#75]
![image](https://user-images.githubusercontent.com/19108762/122019974-592d6a80-cd92-11eb-8788-8036a1ab14a2.png)

Anything stopping this?

**Comment by Zebiano** [comment]
I've also noticed yesterday when running the script that 4x wasn't being activated as expected. Probably some RGB values got changed, and the script doesn't realise it's not on. Will take a look at this later today.

**Comment by kevingrillet** [comment]
`Auto` also sometimes don't work, I think by rewriting it i that way it will work :p

The easy way: Add sleep at the end of `waitBattleStart`

The hard way: Loop until the "on" value is found, while it's not, if "off" color is found tap, else sleep .5s

**Comment by Zebiano** [comment]
Right, the RGB values are still correct. The extra wait does indeed probably fix this. Thanks, Kevin.
