### ISSUE TITLE
Limited offers break the script

### ISSUE THREAD

**Issue by Zebiano** [zebscripts/AFK-Daily#77]
This will most likely be an issue that will never be closed, as this is difficult to fix.

**Comment by kevingrillet** [comment]
Limited offer breaks a check, restart the game, close it (I hope) and keep going 😄

The proper way to check it should be to check a color in the middle of the screen each time this popup can show... so no 😉

**Comment by Zebiano** [comment]
True. Since `v2` of the script, maybe this issue got a little bit less of a problem because the script restarts and attempts again in case something breaks.
