### ISSUE TITLE
Nox not working

### ISSUE THREAD

**Issue by lyte0ne** [zebscripts/AFK-Daily#80]
Hi when launching script from Git Bash, NOX (v. 7.0.1.3) doesn't do anything just opens afk arena and sits at main screen

**Comment by Zebiano** [comment]
Hey there @lyte0ne! Thank you for the issue.

Yeah, we're aware of this. I did not manage to fix it last time I took a look at it and then forgot to update the README... Sorry about that. But I'll try to give it another look this week and see if I can do something about it! 

I'd like to warn you that the next big update to the script will stop supporting Nox, at least for the time being. Maybe if enough people actually show interest in Nox we might re-consider it, but I doubt it. Nox is simply a pain to work with and is not reliable in regards to connecting to it through ADB. Not only that, but we'd need to test everything twice every time a new feature rolls out, once on BS and once on Nox, which is not ideal at all. So please keep this in mind, and consider making the switch to Bluestacks soon if you want to keep on using this script!

If I got some news, I'll write them here.

**Comment by Zebiano** [comment]
Can you tell me which Nox version you are running @lyte0ne? I've been trying to fix this for the past hour without any success with a fresh Nox installation. Though I think my case is even worse than yours, as `adb` doesn't even detect Nox as a device, so the game doesn't even start in the first place. Yours at least starts the game, which is already better than my current situation.

**Comment by lyte0ne** [comment]
Hi sorry for the late answer. I have Nox 7.0.1.3 but as you suggested I will move to BS just in case :) I was using NOX as is lighter on the system then BS.

**Comment by kevingrillet** [comment]
It's strange, if I try with standard adb, Nox is not found, but if I try with their version of adb it finds it... what have they done...

```
MINGW32 /d/Program Files/Nox/bin
$ ./nox_adb.exe devices
List of devices attached
127.0.0.1:62001 device
emulator-5554   device


MINGW32 /d/Users/kevin/Documents/GitHub/AFK-Daily (issue-56)
$ ./adb/platform-tools/adb.exe devices
List of devices attached
emulator-5554   device

```

**Comment by Zebiano** [comment]
@kevingrillet I couldn't even get `nox_adb.exe` to run or recognize me attempting to call it... Double-clicking it actually opens the terminal quickly and shows me the help page of `adb`, so it should at least be working there. But I did not manage to "use" it... Any ideas there?
```sh
nox_adb.exe: command not found
```
Now that I think about it, I did not once try using `./nox_adb.exe`... Maybe that'll do something, though I doubt it.

**Comment by kevingrillet** [comment]
@Zebiano Yep, you need to use `./` because Nox bin folder is [not in your PATH](https://askubuntu.com/a/320657)

**Comment by Zebiano** [comment]
Welp, that did indeed work out... Guess I was too tired yesterday night to think about that. Either way, good news, as I now have hope this works.

Small explanation to our fellow Nox users: you now need to specify the path to the `nox_adb.exe` file on your computer. This file can be found in the same directory as your `Nox.exe` file. When attempting to run the script on Nox, you'll have to provide a path as a second argument like this:
```sh
./deploy.sh nox path/to/nox/bin/nox_adb.exe
```

You can find the directory on Windows by right-clicking the application and clicking on "Go to file location". If you end up in the location of the shortcut, do the same again with the shortcut, it should now take you to a folder called `bin`. This is where you should also find the `nox_adb.exe` file that the script needs.

So for example, my path to `nox_adb.exe` is `S:/Programs/Nox64/bin/nox_adb.exe`, which means I called the script like so:
```sh
./deploy.sh nox S:/Programs/Nox64/bin/nox_adb.exe
```

Hope this helps you out! Any questions feel free to ask them in this issue or under our Discord server.

Lastly, I'd like to again remind you that we don't plan on supporting Nox in the future. Or at least we won't recommend it. We might keep the logic to make the script run on Nox, but we will not test new features on it, so they may work or may not work. In my experience, Nox has been very inconsistent as to finding or not an emulator with `adb`, as well as it throttling the internet connection to the emulator, which in return gives higher load times in-game. This breaks the script, as timings are hardcoded and have Bluestacks in mind. So, if possible, consider the switch to Bluestacks, or keep on using Nox and live life on the edge, up to you! 😉
