### ISSUE TITLE
BlueStacks error

### ISSUE THREAD

**Issue by lyte0ne** [zebscripts/AFK-Daily#81]
Hi as suggested I moved from NOX to BS but now I get this error when launch script

Task: Checking for adb...
Success: Found locally!
Task: Checking for updates...
Success: Checked/Updated!
Task: Searching for config.sh file...
Success: Found!
Task: Validating config.sh...
Success: Passed!
Task: Checking Line endings of file config.sh...
Success: Passed!
Task: Checking Line endings of file afk-daily.sh...
Success: Passed!
Task: Checking last time script was run...
Task: Restarting ADB...
Success: Restarted!
Task: Searching for Bluestacks through ADB...
Success: Found Bluestacks!

Info: Platform: Bluestacks
Info: Script Directory: storage/emulated/0/scripts/afk-arena
Info: Latest tested patch: 1.67.03

error: closed
adb.exe F 07-13 07:52:46  8064 11340 file_sync_client.cpp:503] protocol fault: stat response has wrong message id: 1279869254
adb.exe F 07-13 07:52:47 14152 15984 file_sync_client.cpp:503] protocol fault: stat response has wrong message id: 1279869254
error: closed

BS version is 5.1.100.1020 N32

**Comment by kevingrillet** [comment]
Someone had this problem and posted it on the new [discord](https://discord.gg/Fq2cfqjp8D).
Here is how it was fixes:

1. Restart Bluestacks
2. Restart the terminal
3. Run `./adb/platform-tools/adb kill-server` (from the script folder)
4. Run `./adb/platform-tools/adb start-server`
5. Run the script

Hope this fill fix it for you too.

**Comment by lyte0ne** [comment]
> 4\. ./adb/platform-tools/adb start-server

I get same error... 

I also joined discord :)

**Comment by lyte0ne** [comment]
I have found the issue, USB debugging was off even thou  it was the first thing I did on BS after install
