### ISSUE TITLE
Oak Inn is not accessible if game is updating

### ISSUE THREAD

**Issue by Zebiano** [zebscripts/AFK-Daily#84]
The "game is being updated" icon is right on top of the Oak Inn. There are two possible approaches:
1. Tap a bit lower to not tap the update icon but still tap Oak Inn
2. In case the game is being updated, set `doCollectOakPresents` to `false` mid script to not collect Oak Inn presents

Personally, I prefer the first approach as it's the easiest and most reliable as well. Relying on an RGB check that changes often is not a good idea.

**Comment by kevingrillet** [comment]
Yep, first approach seems better and easier, I'll do it after the current PR is merged 😉
