### ISSUE TITLE
Update how the script checks for a newer script version

### ISSUE THREAD

**Issue by Zebiano** [zebscripts/AFK-Daily#86]
Making use of the `Version` badge will be handy here. Ideally, no `git` command is used, even though maybe they're pretty good to update the script if `git` is present. Not sure what the best way to handle this is yet.

**Comment by kevingrillet** [comment]
We can detect if there is a new version with the current code in the PR.

I was thinking of using something like [that ](https://stackoverflow.com/questions/20645339/download-git-repo-without-all-the-git-stuff)to download the last version, but `wget` is not here by default in `git bash`...

**Comment by kevingrillet** [comment]
> but `wget` is not here by default in `git bash`...

But `curl` can do it: 
```console
$ curl -L -O https://github.com/zebscripts/AFK-Daily/archive/master.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   125  100   125    0     0    419      0 --:--:-- --:--:-- --:--:--   419
100 24014    0 24014    0     0  36460      0 --:--:-- --:--:-- --:--:-- 36460

$ unzip master.zip
Archive:  master.zip
a42ce59da7f59d8d746a7b8db75cecc272a03b81
   creating: AFK-Daily-master/
  inflating: AFK-Daily-master/.gitattributes
  inflating: AFK-Daily-master/.gitignore
  inflating: AFK-Daily-master/LICENSE
  inflating: AFK-Daily-master/README.md
  inflating: AFK-Daily-master/afk-daily.sh
  inflating: AFK-Daily-master/deploy.sh
   creating: AFK-Daily-master/lib/
  inflating: AFK-Daily-master/lib/print.sh

$ rm -v master.zip
removed 'master.zip'
```

**Comment by kevingrillet** [comment]
- Check if git exist: `command -v git &>/dev/null`
  - Yes: `git fetch` then `git status --porcelain` to check if there is an update
    - Yes: `git pull` or `git fetch --all &>/dev/null && git reset --hard origin/master` then `exit 1`
  - No: check with my lib
    - Yes `Curl master.zip`, `mv`, `unzip`, `rm`, `exit 1`
