### ISSUE TITLE
Add Discord github webhook to notify users when there is an update

### ISSUE THREAD

**Issue by kevingrillet** [zebscripts/AFK-Daily#93]
> https://gist.github.com/jagrosh/5b1761213e33fc5b54ec7f6379034a22

Or this video:

> https://www.youtube.com/watch?v=-KDQqWNK3Tw

**Comment by Zebiano** [comment]
This should be fixed now! Hopefully.

**Comment by Zebiano** [comment]
Spoiler alert: it did not.

**Comment by Zebiano** [comment]
Now maybe?

**Comment by Zebiano** [comment]
It worked when staring the repository, but why did it not work when I commented on an issue?

**Comment by Zebiano** [comment]
Apparently only sends an update when you close/open an issue...?
